Repository add-ons/plugin.video.vtm.go, pull requests merged in 2019-09, with the labels that each got.

#62 Add coverage support
  .github/codecov.yml
  .travis.yml
  Makefile
  README.md
  requirements.txt
  resources/lib/kodilogging.py
  resources/lib/plugin.py
  resources/lib/vtmgo.py
  resources/lib/vtmgoauth.py
  resources/lib/vtmgostream.py
  test/run.py
  test/test_routing.py
  test/test_vtmgo.py
  test/userdata/addon_settings.json
  test/userdata/global_settings.json
  test/xbmc.py
  test/xbmcaddon.py
  test/xbmcextra.py
  test/xbmcgui.py
  test/xbmcplugin.py
  test/xbmcvfs.py
Labels: testing

#64 Increase coverage, remove dead code
  resources/lib/kodiutils.py
  test/test_routing.py
  test/userdata/addon_settings.json
  test/xbmc.py
  test/xbmcgui.py
Labels: testing

#67 Rework Kids zone
  resources/language/resource.language.en_gb/strings.po
  resources/lib/plugin.py
  resources/settings.xml
  test/test_routing.py
  test/userdata/addon_settings.json
  test/xbmcaddon.py
Labels: enhancement

#69 Dutch translations
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  test/userdata/global_settings.json
Labels: translations

#53 delay subtitles taking into account advertisements breaks
  Makefile
  resources/lib/kodiutils.py
  resources/lib/vtmgostream.py
  test/test_vtmgo.py
  test/userdata/.keep
  test/xbmcextra.py
  test/xbmcvfs.py
Labels: bug

#71 fix geoblocked videoplayer service api
  resources/lib/vtmgostream.py
  test/test_routing.py
  test/userdata/addon_settings.json
Labels: enhancement

#73 Check translation during tests
  .travis.yml
  Makefile
  resources/language/resource.language.nl_nl/strings.po
Labels: testing, translations

#75 Uniformise travis and local checking flow
  .gitignore
  .travis.yml
  Makefile
  resources/lib/plugin.py
  test/run.py
  test/test_routing.py
  test/test_vtmgo.py
  test/test_vtmgoepg.py
  test/userdata/.keep
  test/userdata/addon_settings.json
  tox.ini
Labels: release, testing
