Repository add-ons/plugin.video.vtm.go, pull requests merged in 2020-07, with the labels that each got.

#183 Improve subtitle behaviour using PlayerMonitor
  resources/lib/kodiwrapper.py
  resources/lib/modules/player.py
  resources/lib/service.py
  resources/lib/vtmgo/vtmgostream.py
  tests/xbmc.py
Labels: bug, enhancement

#191 Use sake for Kodi stubs
  .github/workflows/ci.yml
  .gitignore
  Makefile
  plugin.py
  requirements.txt
  resources/lib/kodilogging.py
  resources/lib/kodiwrapper.py
  resources/lib/modules/player.py
  resources/lib/service.py
  resources/lib/vtmgo/vtmgoauth.py
  resources/lib/vtmgo/vtmgostream.py
  tests/__init__.py
  tests/home/addons/inputstream.adaptive/addon.xml
  tests/home/addons/script.module.inputstreamhelper/addon.xml
  tests/home/system/.gitkeep
  tests/home/userdata/guisettings.xml
  tests/run.py
  tests/test_routing.py
  tests/test_vtmgo.py
  tests/test_vtmgoepg.py
  tests/userdata/addon_settings.json
  tests/userdata/credentials.json.example
  tests/userdata/global_settings.json
  tests/xbmc.py
  tests/xbmcaddon.py
  tests/xbmcextra.py
  tests/xbmcgui.py
  tests/xbmcplugin.py
  tests/xbmcvfs.py
  tox.ini
Labels: testing

#192 Make authentication more robust
  .gitignore
  resources/lib/vtmgo/vtmgo.py
  resources/lib/vtmgo/vtmgoauth.py
  resources/lib/vtmgo/vtmgostream.py
Labels: enhancement
