Repository add-ons/plugin.video.vtm.go, pull requests merged in 2020-03, with the labels that each got.

#149 First public release
  CHANGELOG.md
  Makefile
  addon.xml
Labels: release

#157 Fix encoding of profile name
  resources/lib/modules/authentication.py
  resources/lib/vtmgo/vtmgo.py
Labels: bug

#159 Small translation fixes
  resources/language/resource.language.nl_nl/strings.po
Labels: translations

#160 Fix text encoding when getting data from VTM GO Api
  resources/lib/vtmgo/vtmgo.py
Labels: bug

#162 Allow browsing the addon without authentication
  addon.xml
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/kodiwrapper.py
  resources/lib/modules/player.py
  resources/lib/plugin.py
  test/test_vtmgo.py
Labels: enhancement, testing

#158 Various check fixes
  .pylintrc
  Makefile
  resources/lib/kodiwrapper.py
  resources/lib/modules/__init__.py
  resources/lib/modules/authentication.py
  resources/lib/modules/catalog.py
  resources/lib/modules/channels.py
  resources/lib/modules/menu.py
  resources/lib/modules/tvguide.py
  resources/lib/plugin.py
  resources/lib/service.py
  resources/lib/vtmgo/vtmgo.py
  resources/lib/vtmgo/vtmgoauth.py
  resources/lib/vtmgo/vtmgostream.py
  test/run.py
  test/test_routing.py
  test/test_vtmgo.py
  test/test_vtmgoepg.py
  test/xbmc.py
  tox.ini
Labels: testing

#163 Add .gitattributes file with export-ignore to clean up the zip downloads
  .gitattributes
Labels: release

#167 Add error handling for HTTP 426
  resources/language/resource.language.en_gb/strings.po
  resources/language/resource.language.nl_nl/strings.po
  resources/lib/modules/authentication.py
  resources/lib/modules/catalog.py
  resources/lib/vtmgo/vtmgo.py
  resources/lib/vtmgo/vtmgoauth.py
Labels: bug
